language: node_js
dist: xenial
node_js:
  - lts/*

addons:
  sonarcloud:
    organization: "sephiroth-j-github"
    token: $SONAR_TOKEN
script:
  - npm run coverage
  - npm run sonar
  - sonar-scanner

# access full scm history
# https://docs.travis-ci.com/user/sonarcloud/#accessing-full-scm-history
git:
  depth: false
